tasks:
  - init: bin/setup
    command: |
      bundle install
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
  - name: docker
    init: |
      docker compose -f docker-compose.yml up
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    #command: | 
    #  export GITPOD_IP=$(curl ifconfig.me)
    #  source "$THEIA_WORKSPACE_ROOT/bin/rds-update-sg-rule"

ports:
  - name: psql-database
    port: 5432
    visibility: public
  - name: app
    port: 3000
    visibility: public

vscode:
  extensions:
    - cweijan.vscode-postgresql-client2
    - amazonwebservices.aws-toolkit-vscode
    - karunamurti.haml